parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    assets_folder: "sass"

    mail_from: unoegohh@gmail.com
    mail_to: unoegohh@gmail.com
    mail_name:  'Заказ с сайта'

    sass_folder: /var/lib/gems/1.8/gems/sass-3.2.9/bin/sass
    compass_folder: /var/lib/gems/1.8/gems/compass-0.12.2/bin/compass