parameters:
#    unoegohh_static_page.example.class: Unoegohh\StaticPageBundle\Example

services:
#    unoegohh_static_page.example:
#        class: %unoegohh_static_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
