parameters:
#    unoegohh_shop.example.class: Unoegohh\ShopBundle\Example

services:
#    unoegohh_shop.example:
#        class: %unoegohh_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
